import Head from "next/head";
import Background from "@/src/components/Background/Background";
import About from "@/src/components/AboutUs/About";
import Outcomes from "@/src/components/Stats/Outcomes";
import Card from "@/src/components/Card/Card";
import Slider from "@/src/components/Slider/Slider";
import { SliderData } from "@/src/components/Slider/SliderData";
import Services from "@/src/components/Services/Services";
import EventAndProgram from "@/src/components/events";
import TeamMember from "@/src/components/Team/TeamMember";
import Contact from "@/src/components/Contact/Contact";
import Footer from "@/src/components/HeaderFooter/Footer";
import Navbar from "@/src/components/HeaderFooter/Nav";
import ScrollTopButton from "@/src/components/utils/BackToTop";
export default function Home() {


  return (
    <>
      <div>
        <Head>
          <title>Brainycube Research Organization</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar />
        <Background
          heading="Brainycube Research Organization"
          message="Keep learning and exploring, you are the future of research!"
        />
        <About />
        <Outcomes />
        <Card />
        <Slider slides={SliderData} />
        <Services />
        <EventAndProgram />
        <TeamMember />
        <Contact />
        <Footer />
        <ScrollTopButton/>
        
      </div>
    </>
  );
}
