import Head from "next/head";
import Background from "@/src/components/Background/Background";
import About from "@/src/components/AboutUs/About";
export default function Home() {
  return (
    <>
      <div>
        <Head>
          <title>Brainycube Research Organization</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {/* <h1 className="text-6xl font-raleway text-primary-green text-center">
          Brainycube Website
        </h1> */}
        <Background
          heading="Brainycube Research Organization"
          message="Keep learning and exploring, you are the future of research!"
        />
        <About/>
      </div>
    </>
  );
}
